# Generated by Django 3.2 on 2021-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bmi',
            field=models.FloatField(),
        ),
    ]
